---
- hosts: pi2
  become: true
  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Firefox ESR (Webbrowser)
      ansible.builtin.apt:
        name: firefox-esr
        state: present

    - name: Install Thunderbird (E-Mail client)
      ansible.builtin.apt:
        name: thunderbird
        state: present

    - name: Install Vim (Text editor)
      ansible.builtin.apt:
        name: vim
        state: present

    - name: Install OpenVPN (VPN client)
      ansible.builtin.apt:
        name: openvpn
        state: present

    - name: Install Samba (File sharing)
      ansible.builtin.apt:
        name: samba
        state: present

    - name: Install htop (System monitor)
      ansible.builtin.apt:
        name: htop
        state: present
