---
- name: Install simple software on Raspberry Pi
  hosts: localhost
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install htop (process viewer)
      apt:
        name: htop
        state: present

    - name: Install vim (text editor)
      apt:
        name: vim
        state: present

    - name: Install git (version control)
      apt:
        name: git
        state: present

    - name: Install tree (directory viewer)
      apt:
        name: tree
        state: present
