---
- hosts: localhost
  become: yes
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install git
      apt:
        name: git
        state: present

